baseurl = "http://seville-jam.es/"
languageCode = "en-us"
theme = "lanyon-hugo"

[params]
  Title = "Seville Jenkins Area Meetup"
  #Tagline = "A Jekyll theme"
  Author = "Mark Otto"
  DateForm = "Jan 2 2006"
