baseurl = "http://seville-jam.es/"
languageCode = "en-us"
theme = "lanyon-hugo"

[params]
  Title = "Seville Jenkins Area Meetup"
  #Tagline = "A Jekyll theme"
  Author = "Manuel Recena Soto"
  DateForm = "Jan 2 2006"

#[permalinks]
#  post = ":title/"
#  fixed = ":title/"
